export { default as Home } from './Home'
export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as Banner } from './Banner'
export { default as Middlepage } from './Middlepage'